config/routes.rb
Rails.application.routes.draw do

  resources :outlets do
    collection do
    get 'search'
  end
end
  resources :companies do
    collection do
    get 'search'
  end
end

  resources :products do
    collection do
    get 'search'
  end
end

  resources :categories do
    collection do
    get 'search'
  end
end
  root "categories#index"

end

app/models/outlet.rb
class Outlet < ActiveRecord::Base
  searchkick
  belongs_to :company

  has_attached_file :image, styles: { :medium => "300x300#" }
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/controllers/outlets_controller.rb
class OutletsController < ApplicationController
  before_action :set_outlet, only: [:show, :edit, :update, :destroy]

  def search
    if params[:search].present?
      @outlets = Outlet.search(params[:search])
    else
      @outlets = Outlet.all
    end
 end

  # GET /outlets
  # GET /outlets.json
  def index
    @outlets = Outlet.all
  end

  # GET /outlets/1
  # GET /outlets/1.json
  def show
  end

  # GET /outlets/new
  def new
    @outlet = Outlet.new
  end

  # GET /outlets/1/edit
  def edit
  end

  # POST /outlets
  # POST /outlets.json
  def create
    @outlet = Outlet.new(outlet_params)

    respond_to do |format|
      if @outlet.save
        format.html { redirect_to @outlet, notice: 'Outlet was successfully created.' }
        format.json { render :show, status: :created, location: @outlet }
      else
        format.html { render :new }
        format.json { render json: @outlet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /outlets/1
  # PATCH/PUT /outlets/1.json
  def update
    respond_to do |format|
      if @outlet.update(outlet_params)
        format.html { redirect_to @outlet, notice: 'Outlet was successfully updated.' }
        format.json { render :show, status: :ok, location: @outlet }
      else
        format.html { render :edit }
        format.json { render json: @outlet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /outlets/1
  # DELETE /outlets/1.json
  def destroy
    @outlet.destroy
    respond_to do |format|
      format.html { redirect_to outlets_url, notice: 'Outlet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_outlet
      @outlet = Outlet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def outlet_params
      params.require(:outlet).permit(:title, :description, :price, :outlet, :company_id, :image)
    end
end

app/helpers/outlets_helper.rb
module OutletsHelper
end

app/views/outlets/_form.html.erb
<%= form_for @outlet, html: { :multipart => true } do |f| %>
  <% if @outlet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@outlet.errors.count, "error") %> prohibited this outlet from being saved:</h2>

      <ul>
      <% @outlet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :outlet %><br>
    <%= f.text_field :outlet %>
  </div>
  <div class="field">
    <%= f.label :company_id %><br>
    <%= f.text_field :company_id %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/outlets/edit.html.erb
<h1>Editing Electronics</h1>

<%= render 'form' %>

<%= link_to 'Show', @outlet %> |
<%= link_to 'Back', outlets_path %>

app/views/outlets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Electronics</h1>


<div class="container ">
<div class="row">
    <% @outlets.each do |outlet| %>
    <div class="col-md-4">
      <div class="sec">


        <%= link_to (image_tag outlet.image.url(:medium), class: 'img'), outlet%>
        <div class="under">
        <hr class="line">
        <h3 class="cheading">
        <%= outlet.title %></h3>
        <%= outlet.description %>
        <%= outlet.price %>
        <%= outlet.outlet %>
        <%= outlet.company %>
        <%= link_to 'Show', outlet %>
        <%= link_to 'Edit', edit_outlet_path(outlet) %>
        <%= link_to 'Destroy', outlet, method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

<%= link_to 'New Outlet', new_outlet_path %>

app/views/outlets/new.html.erb
<h1>New Outlet</h1>

<%= render 'form' %>

<%= link_to 'Back', outlets_path %>

app/views/outlets/search.html.erb
<div class="container ">
<div class="row">
    <% @outlets.each do |outlet| %>
    <div class="col-md-4">
      <div class="sec">


        <%= link_to (image_tag outlet.image.url(:medium), class: 'img'), outlet%>
        <div class="under">
        <hr class="line">
        <h3 class="cheading">
        <%= outlet.title %></h3>
        <%= outlet.description %>
        <%= outlet.price %>
        <%= outlet.outlet %>
        <%= outlet.company %>
        <%= link_to 'Show', outlet %>
        <%= link_to 'Edit', edit_outlet_path(outlet) %>
        <%= link_to 'Destroy', outlet, method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/outlets/show.html.erb
<p id="notice"><%= notice %></p>

<%= image_tag @outlet.image.url(:medium) %>       

<p>
  <strong>Title:</strong>
  <%= @outlet.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @outlet.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @outlet.price %>
</p>

<p>
  <strong>Outlet:</strong>
  <%= @outlet.outlet %>
</p>

<p>
  <strong>Company:</strong>
  <%= @outlet.company %>
</p>

<%= link_to 'Edit', edit_outlet_path(@outlet) %> |
<%= link_to 'Back', outlets_path %>