config/routes.rb
Rails.application.routes.draw do

  resources :outlets do
    collection do
    get 'search'
  end
end
  resources :companies do
    collection do
    get 'search'
  end
end

  resources :products do
    collection do
    get 'search'
  end
end

  resources :categories do
    collection do
    get 'search'
  end
end
  root "categories#index"

end

app/models/company.rb
class Company < ActiveRecord::Base
  searchkick
  belongs_to :product
  has_many :outlets

  has_attached_file :image, styles: { :medium => "300x239#" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  def search
    if params[:search].present?
      @companies = Company.search(params[:search])
      else
        @companies = Company.all
      end
   end

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:title, :price, :ouelt, :product_id, :image)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= form_for @company, html: { :multipart => true } do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :outlet %><br>
    <%= f.text_field :outelt %>
  </div>
  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.text_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
  <div class="container ">
  <div class="row">
    <h1>Categories</h1>
    <% @companies.each do |company| %>
    <div class="col-md-4">

      <div class=" img_b cate">
    <%= link_to (image_tag company.image.url(:medium), class: 'cimg') %>
    <div class="cinfo">
    <p class="ctitle"> <%= company.title %> </p>
    <!-- <p class="cprice">  <span class="pred"> <%= company.price %> </span> </p>
    <p class="coutlet"> <span class = "pwhite" > <%= company.outelt %> </span> </p> -->
  </div>


    <!-- <%= link_to 'Show', company %>
    <%= link_to 'Edit', edit_company_path(company) %>
    <%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %> -->
  </div>
</div>
<% end %>

</div>
</div>
<!-- <%= link_to 'New Company', new_company_path %> -->

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form' %>

<%= link_to 'Back', companies_path %>

app/views/companies/search.html.erb
<div class="container ">
<div class="row">
  <% @companies.each do |company| %>
  <div class="col-md-4">
    <div class="sec">

      <%= link_to (image_tag company.image.url(:medium), class: 'img'), outlets_path%>
      <div class="under">
      <hr class="line">
      <h3 class="cheading">
      <%= company.title %></h3>
      <%= company.product %>
      <%= link_to 'Show', company %>
      <%= link_to 'Edit', edit_company_path(company) %>
      <%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
    </div>
  </div>
  <% end %>
</div>
</div>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @company.title %>
</p>

<p>
  <strong>Product:</strong>
  <%= @company.product %>
</p>
<%= image_tag @company.image.url(:medium) %>

<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>