config/routes.rb
Rails.application.routes.draw do

  resources :outlets do
    collection do
    get 'search'
  end
end
  resources :companies do
    collection do
    get 'search'
  end
end

  resources :products do
    collection do
    get 'search'
  end
end

  resources :categories do
    collection do
    get 'search'
  end
end
  root "categories#index"

end

app/models/category.rb
class Category < ActiveRecord::Base
  searchkick
  has_many :products

  has_attached_file :image, styles: { :medium => "300x239#" }
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]


  def search
    if params[:search].present?
      @categories = Category.search(params[:search])
    else
      @categories = Category.all
    end
 end

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:title, :price, :outlet, :image)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
	def print_price(price)
		"ksh#{price}"
	end
end

app/views/categories/_form.html.erb
<%= form_for @category, html: { :multipart => true } do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :outlet %><br>
    <%= f.text_field :outlet %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
  <div class="bgimg">
    <div class="mainh">
      <h1>Welcome to <span class="bar">Bargain.</span></h1><span class="hspa">Compare Prices of Electronics</span>
    </div>
    <h3>Search By</h3>
    <div class="bs"> <%= button_to "Category", companies_path, :class => "button", :method => :get  %> </div>
    
    <div class="down"> <img  src ="assets/scrollArrow.png" class="sdown"> </div>


  </div>


<div class="container">
<div class="row">


<!--

  <div class="categories col-md-12">
    <h1>Categories</h1>
    <hr>
  <ul>
    <li>
        <a href="#">Foods & Groceries</a>

  </li>
  <li>
      <a href="#">Electronics</a>
</li>
<li>
    <a href="#">Clothes</a>
</li>
<li>
    <a href="#">Shoes</a>
</li>
</ul>
</div> -->

  <h1 class="cheading">Recently Compared Items </h1>

    <% @categories.each do |category| %>
        <div class="col-md-4">

          <div class=" img_b">
        <%= link_to (image_tag category.image.url(:medium), class: 'cimg'), products_path(category_id: category.id)%>
        <hr>
        <div class="cinfo">
        <p class="ctitle"> <%= category.title %> </p>
        <p class="cprice">  <span class="pred"> <%= print_price ( category.price ) %> </span> </p>
        <p class="coutlet"> <span class = "pwhite" > <%= category.outlet %> </span> </p>
      </div>


        <%= link_to 'Show', category %>
        <%= link_to 'Edit', edit_category_path(category) %>
        <%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %> 
      </div>
    </div>
    <% end %>

</div>
</div>
<!-- <%= link_to 'New Category', new_category_path %> -->

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/search.html.erb
<div class="container ">
<div class="row">
    <% @categories.each do |category| %>
        <div class="col-md-4">
          <div class="sec">

        <%= link_to (image_tag category.image.url(:medium), class: 'img'), products_path(category_id: category.id)%>
        <div class="under">
        <hr class="line">
        <h3 class="cheading">
        <%= category.title %></h3>
       <!--  <%= link_to 'Show', category %>
        <%= link_to 'Edit', edit_category_path(category) %>
        <%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %> -->
      </div>
      </div>
    </div>


    <% end %>
  </div>
</div>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @category.title %>
</p>

<%= image_tag @category.image.url(:medium) %>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>