config/routes.rb
Rails.application.routes.draw do

  resources :outlets do
    collection do
    get 'search'
  end
end
  resources :companies do
    collection do
    get 'search'
  end
end

  resources :products do
    collection do
    get 'search'
  end
end

  resources :categories do
    collection do
    get 'search'
  end
end
  root "categories#index"

end

app/models/product.rb
class Product < ActiveRecord::Base

  searchkick
  belongs_to :category
  has_many :companies
# papaerclip for smaller image
  has_attached_file :image, styles: { :medium => "300x239#" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

# paperclip for larger image on hover
  has_attached_file :avatar, styles: {  :large => "800x800" }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/


end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def search
    if params[:search].present?
      @products = Product.search(params[:search])
    else
      @products = Product.all
    end
 end

  # GET /products
  # GET /products.json
  def index
    puts "************^^^^^^^^^" + params.inspect
    @products = Product.where("category_id = ?",params[:category_id])

  end

  # GET /products/1
  # GET /products/1.json
  def show
    # @products = Product.where("category_id = 1",params[:product])
    @products = Product
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :price, :outlet, :desription, :location, :category_id, :image, :avatar)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
	def print_price(price)
		"ksh#{price}"
	end
end

app/views/products/_form.html.erb
<%= form_for @product, html: { :multipart => true } do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price%>
  </div>
  <div class="field">
    <%= f.label :outlet %><br>
    <%= f.text_field :outlet%>
  </div>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :desription%>
  </div>

  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location%>
  </div>
  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.text_field :category_id %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
    <div class="field">
    <%= f.label :avatar %><br>
    <%= f.file_field :avatar %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>



  <div class="container ">
    <div class="row ptop">
    <% @products.each do |product| %>

        <div class="col-md-4">

          <div class=" img_b">
        <%= link_to (image_tag product.image.url(:medium),class: 'cimg'),product%>
        <hr>
        <div class="cinfo">
        <p class="ctitle">  <%= product.title %> </p>
        <p class="cprice"> <span class="pred"><%= print_price (product.price) %> </span> </p>
        <p class="coutlet"> <span class = "pwhite" > <%= product.outlet %> </span> </p>
      </div>


        <%= product.category %> 
<!-- 
         <%= link_to 'Show', product %>
        <%= link_to 'Edit', edit_product_path(product) %>
        <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %> 
 -->
      <!-- <div class="col-md-6 ptitle"> -->

        <!-- <ul>
          <li class="price">Price: ksh30,000 </li>
          <li class="outlet">Outlet: Nakumatt </li>
          <li class="stock"> Stock: In stock </li>
        </ul>
        <h3 class="desctitle"> Description</h3>
        <p descp>Double layer, sheer mini skirt with metallic stars and beaded waistband.
          Comes with lining and zip closure Double layer, sheer mini skirt with metallic stars
          and beaded waistband. Comes with lining and zip closure
        </p>
      </div> -->
    </div>
  </div>
  <% end %>
  </div>
</div>

 <!-- <%= link_to 'New Product', new_product_path %> -->

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/search.html.erb
<div class="container ">
  <div class="row">
  <% @products.each do |product| %>
  <div class="col-md-4">
    <div class="sec">

      <%= link_to (image_tag product.image.url(:medium),class: 'img'), companies_path%>
      <div class="under">
      <hr class="line">
      <h3 class="cheading">
      <%= product.title %></h3>
      <%= product.category %>
      <%= link_to 'Show', product %>
      <%= link_to 'Edit', edit_product_path(product) %>
      <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
    </div>
  </div>
  <% end %>
</div>
</div>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>


<div class="row wrapper ptop">

  <div class="col-md-6">
  <%= image_tag @product.image.url(:medium), :class => " pimg", :id => "zoom_01", :'data-zoom-image' => @product.avatar.url(:large) %>
   
    <script type="text/javascript">
        $('#zoom_01').elevateZoom();
    </script>
</div>
<div class="col-md-6 pinfo">
<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>
<p>
  <strong>Price:</strong>
  <%=print_price (@product.price) %>
</p>

<strong>Description:</strong>
  <%= @product.desription %>
</p>

<strong>Location:</strong>
  <%= @product.location %>
</p>
<!-- <p> -->
  <!-- <strong>Category:</strong>
  <%= @product.category %>
</p> -->
</div>

</div>

</div>

 <%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path(@product) %> 